const { chromium } = require('playwright');
const fs = require('fs');
const FRONT = 'http://127.0.0.1:5173';
const env = JSON.parse(fs.readFileSync('/tmp/verify_summary_env.json', 'utf8'));
(async () => {
 const browser = await chromium.launch({ headless: true });
 const context = await browser.newContext({ viewport: { width: 1536, height: 1120 } });
 await context.addInitScript((session)=>localStorage.setItem('notebooklm-session', JSON.stringify(session)), {token:env.token,user:{id:env.userId,name:env.username,email:env.email}});
 const page = await context.newPage();
 await page.goto(`${FRONT}/notebook/${env.notebookId}?articleId=${env.articleId}`, { waitUntil:'domcontentloaded'});
 await page.waitForSelector('.nb-layout', {timeout:30000});
 await page.waitForTimeout(4000);
 const tocCount = await page.locator('.nb-toc-item').count();
 const contentCount = await page.locator('.nb-markdown-content').count();
 const hint = await page.locator('.nb-empty-center p, .nb-processing-hint').allTextContents().catch(()=>[]);
 const bodyText = await page.locator('.nb-markdown-content').first().innerText().catch(()=> '');
 await page.screenshot({path:'/tmp/debug-seed-article.png', fullPage:true});
 await browser.close();
 console.log(JSON.stringify({tocCount, contentCount, hint, bodyText: bodyText.slice(0,120)}, null, 2));
})();
